FROM grafana/grafana:7.1.3

RUN  wget https://github.com/ilgizar/ilgizar-candlestick-panel/raw/master/pack/ilgizar-candlestick-panel.zip -O /tmp/plugin.zip && unzip /tmp/plugin.zip -d /var/lib/grafana/plugins
